- name: upgrade all packages
  yum: name=* state=latest
  tags: [default]

- name: requirements packages
  yum:
    name:
      - initscripts
      - shadow-utils

- name: set timezone
  timezone:
    name: America/Lima

- name: disable sendmail
  service:
    name: sendmail
    enabled: no